### PR TITLE
Theme + Colorizer for Ember Handlbars and Babel ES6

### PR DESCRIPTION
**Pull request by EWhite613**
# minor

### CODE REVIEW

**Comment by EWhite613** [comment]
Controller
Controller
Route
Route

Handlebars
screen shot 2016-04-14 at 9 37 46 am
screen shot 2016-04-14 at 9 37 54 am

General Javascript
screen shot 2016-04-14 at 9 38 51 am

**Comment by sglanzer-fire** [comment]
This is looking really good - I just have a few comments based on the screenshots you provided.  I was going to note them here, but it's going to be easier to discuss this in person where I can point to what I'm talking about, so I'll drop by in the morning to discuss

**Comment by sglanzer-fire** [comment]
I'm not going to make it into the office for a bit so:
- Blue text on the last element of a property chain?  extend, service, get
- Can we color Ember keywords differently? actions {, computed., model(, etc.
- #each is blue, doesn't match other keywords
- Love the italic use on _as_
- Can we stylize onClick as an action hook, ditto for the 'handler'

**Comment by EWhite613** [comment]
@sglanzer 
1.   They're blue because Babel marks them as `function-call`. Do you want some other color for this?
2.   I can but than I half to copy the Babel colorizer extension. Since VsCode I don't think handles extending colorizers well (I'll attempt to). So if I can't get it to extend somehow I'll have to just copy-paste Babel colorizer and add our own stuff, still want to do it if this is the case?
3. So I fixed `#each` in one of the commits after the image. So looks like this
   screen shot 2016-04-15 at 10 13 42 am

4.1 For both onClick and on-click? And do we have a unique color for an action hook? Is the `handler` always the first parameter of `<(/{{>action`?

**Comment by EWhite613** [comment]
Re: 2

Apparently I can extend. http://stackoverflow.com/a/35905775/3771965
I remember trying this with handlebars and it didn't work. But that's probably because vscode doesn't use .tmLanguage to handle handlebars

**Comment by sglanzer-fire** [comment]
1. Ok, that's fine then - I wasn't sure if they did it for all properties, but that makes sense
2. Ok - it would be nice, but it's not a show-stopper, so I won't hold anything up on that
3. Excellent, thanks
4. Yeah, I'd do both - if you look back at the brackets theme work there are colors for events/actions - it was a blue and then a lighter blue for the handler - the handler is always the first positional param

**Comment by sglanzer-fire** [comment]
If we can address 4. then I'm completely happy with this

**Comment by EWhite613** [comment]
@sglanzer 

New colors for onclick and action handler 

screen shot 2016-04-15 at 12 02 43 pm

**Comment by EWhite613** [comment]
Now that I post it I see I missed `on-click=handler`. I'll fix after lunch

**Comment by EWhite613** [comment]
@sglanzer 
Fixed it
screen shot 2016-04-15 at 1 05 59 pm

**Comment by sglanzer-fire** [comment]
Nice!

**Pull request merged**
